# Generated by Django 2.2.19 on 2022-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("slug", models.CharField(max_length=25)),
                ("description", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Рок"),
                    ("E", "Электроника"),
                    ("P", "Поп"),
                    ("C", "Классика"),
                    ("O", "Саундтреки"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
