# Generated by Django 2.2.16 on 2022-04-20 14:07

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220420_1705'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_not__user',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('user')), name='author_not_user'),
        ),
    ]
