# Generated by Django 2.2.16 on 2022-04-20 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_auto_20220420_1707'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('author', 'user')},
        ),
    ]
